[package]
name = "spotify-autoskip"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
tokio = { version = "1.49.0", features = ["rt", "macros", "time"] }
zbus = { version = "5.13.1", features = ["tokio"] }
